# Generated by Django 4.2.3 on 2023-07-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название категорий"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Символьный код")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/%Y/cat/",
                        verbose_name="Изображение",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("slug", models.SlugField(unique=True, verbose_name="Символьный код")),
                ("image", models.URLField(verbose_name="Адрес изображения")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "number_of_persons",
                    models.CharField(max_length=10, verbose_name="Количество игроков"),
                ),
                (
                    "duration",
                    models.CharField(max_length=10, verbose_name="Продолжительность"),
                ),
                (
                    "age_limit",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Ограничение по возрасту"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "availability",
                    models.BooleanField(default=True, verbose_name="Доступность"),
                ),
                (
                    "number_of_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во просмотров"
                    ),
                ),
                (
                    "number_of_sales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во покупок"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="catalog.category",
                        verbose_name="Категория игры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
                "ordering": ["-id"],
            },
        ),
    ]
