# Generated by Django 4.2.3 on 2023-07-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория игр",
                "verbose_name_plural": "Категории игр",
            },
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="catalog.category",
                verbose_name="Категория игры",
            ),
        ),
    ]
