# Generated by Django 4.2.3 on 2023-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_category_options_alter_game_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="categories/%Y/cat/", verbose_name="Изображение"
            ),
        ),
    ]
