# Generated by Django 4.2.3 on 2023-07-12 21:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("catalog", "0003_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
