# Generated by Django 4.2.3 on 2023-07-15 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_game_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 15, 10, 45, 25, 591485, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления товара",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="updated_at",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
