# Generated by Django 4.2.3 on 2023-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(default="1111", max_length=20),
        ),
    ]
