# Generated by Django 4.2.3 on 2023-07-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0002_profile_password"),
        ("orders", "0002_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="profile_app.profile",
                verbose_name="Заказы",
            ),
            preserve_default=False,
        ),
    ]
