# Generated by Django 4.2.3 on 2023-07-14 06:45

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("profile_app", "0002_profile_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Название поста"),
                ),
                (
                    "p1",
                    models.TextField(blank=True, null=True, verbose_name="Параграф 1"),
                ),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/posts/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "p2",
                    models.TextField(blank=True, null=True, verbose_name="Параграф 2"),
                ),
                (
                    "img2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/posts/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "p3",
                    models.TextField(blank=True, null=True, verbose_name="Параграф 3"),
                ),
                (
                    "img3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/posts/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "other_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Остальной текст"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="profile_app.profile",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
    ]
