# Generated by Django 4.2.3 on 2023-07-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=1, unique=True, verbose_name="Символьный код"
            ),
            preserve_default=False,
        ),
    ]
