# Generated by Django 4.2.3 on 2023-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="availability",
            field=models.BooleanField(default=True, verbose_name="Доступность"),
        ),
    ]
