# Generated by Django 4.2.3 on 2023-07-15 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
